const REQUEST_SUBREDDITS = 'REQUEST_SUBREDDITS';
const RECEIVE_SUBREDDITS = 'RECEIVE_SUBREDDITS';
const REQUEST_POSTS = 'REQUEST_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';


export default {
REQUEST_SUBREDDITS,
RECEIVE_SUBREDDITS,
REQUEST_POSTS,
RECEIVE_POSTS
};
